replace array with variable size with vector, this should help clang compiler to compile our source code

diff --git a/tests/t_utf8input b/tests/t_utf8input
--- a/tests/t_utf8input
+++ b/tests/t_utf8input
@@ -16,7 +16,7 @@ for i in `../src/sdcv --utf8-input -n человек 2>&1`; do
 done
 
 if [ $j -eq 1 ]; then
-	echo "empty results of search: test failed" >&2
+	echo "$0: empty results of search: test failed" >&2
 	exit 1
 fi
 
